name: studio2stadium

services:
  db:
    image: postgres:18
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command:
      ["redis-server", "--save 20 1", "--loglevel warning", "--requirepass ${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017"
    volumes:
      - mongodb:/var/lib/mongodb

  event-server:
    build:
      context: ./apps/event-server
      dockerfile: Dockerfile
    container_name: event-server
    volumes:
      - ./apps/event-server:/app
      - ./apps/event-server/cmd/.env:/app/cmd/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo

volumes:
  cache:
    driver: local
  pgdata:
  mongodb:
